export const BookGenres = [
    "Ficção Científica", 
    "Fantasia", 
    "Romance", 
    "Mistério", 
    "Suspense", 
    "Terror", 
    "Aventura", 
    "História", 
    "Biografia", 
    "Autobiografia", 
    "Autoajuda", 
    "Poesia", 
    "Drama", 
    "Comédia", 
    "Policial", 
    "Thriller", 
    "Fantasia Urbana", 
    "Distopia", 
    "Infantil", 
    "Juvenil",
    "Outro",
]